# Generated by Django 5.2.7 on 2025-10-15 07:42

import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcde123456', length=6, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/category')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcde123456', length=6, max_length=20, prefix='ven', unique=True)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/vendor')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid email', regex='^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$')])),
                ('mobile', models.CharField(validators=[django.core.validators.RegexValidator(message='Invalid mobile numebr', regex='^\\+?(?:[0-9] ?){6,14}[0-9]$')])),
                ('address', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('website', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcde123456', length=6, max_length=20, prefix='prd', unique=True)),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/default.png', upload_to='images/products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('in_stock', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category')),
                ('tags', taggit.managers.TaggableManager(blank=None, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('vendor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('feature_value', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
