# Generated by Django 5.2.7 on 2025-11-18 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_view', to='home.product'),
        ),
    ]
