# Generated by Django 5.2.7 on 2025-11-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_productviews_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
