# Generated by Django 5.2.7 on 2025-11-22 10:58

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_price_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456', length=6, max_length=20, prefix='ord', unique=True),
        ),
    ]
